Add control to stop/start the waydroid session
sailfishos-open/waydroid-runner pull request #3
Opened 2021-12-09 18:11 UTC by piggz

Helps in the case where waydroid thinks the session is running after a
reboot or waydroid-runner was killed, leaving the session running.

2021-12-09 19:51 UTC, rinigus requested changes
Looks good, just few changes suggested.

`m_statusCode` variable should be `m_status_code`, as all vars are in the class. Note that QML-exposed, it is `statusCode`, as you have already. As the same notation runs through all code with the other vars as well, let's keep it here too.

For our future sanity, would be advantageous to define an `enum` with the values of status codes. While in QML we would use the values as-is, it is good to have a reference list with the meaning. Please add that to the header and use in the code (header for m_status_code initialization) and use in cpp.

Note, that probably we can also allow to start Android for status code -3.

2021-12-09 21:57 UTC, piggz commented
I think I addressed all the comments, and also made use of enum value name in QML

2021-12-10 18:30 UTC, rinigus commented
@piggz: I have added one commit that corrects the logic in the case of unexpected Wayland display. It could occur if someone managed to start Waydroid session just after we checked that session is not running and waydroid display was set according to the another session. So, I expect we need to close it in this case. Hence the change. 

If it is OK, I will merge PR as it is.

2021-12-10 18:30 UTC, rinigus approved these changes

2021-12-10 18:51 UTC, piggz commented
go for it, i wasnt able to test that case, and is likely rare

2021-12-10 18:52 UTC, merged